const Data = [
    {
        "id": 1,
        "name": "Men's Casual Shirt",
        "slug": "a",
        "category": "Men",
        "price": 25.99,
        "description": "A stylish and comfortable casual shirt made from premium cotton.",
        "sizes": ["S", "M", "L", "XL"],
        "colors": ["Blue", "White", "Black"],
        "stock": 50,
        "image": "/images/bestSellingProducts/product-cover-51.png"
    },
    {
        "id": 2,
        "name": "Women's Summer Dress",
        "slug": "b",
        "category": "Women",
        "price": 35.99,
        "description": "A light and breezy summer dress perfect for any occasion.",
        "sizes": ["XS", "S", "M", "L"],
        "colors": ["Yellow", "Pink", "Green"],
        "stock": 30,
        "image": "/images/bestSellingProducts/product-cover-51.png"
    },
    {
        "id": 3,
        "name": "Men's Denim Jeans",
        "slug": "c",
        "category": "Men",
        "price": 45.99,
        "description": "Durable and stylish denim jeans with a slim fit design.",
        "sizes": ["28", "30", "32", "34", "36"],
        "colors": ["Blue", "Black"],
        "stock": 40,
        "image": "/images/bestSellingProducts/product-cover-53.png"
    },
    {
        "id": 4,
        "name": "Women's Office Blazer",
        "slug": "d",
        "category": "Women",
        "price": 50.99,
        "description": "A formal blazer suitable for office wear and professional settings.",
        "sizes": ["S", "M", "L", "XL"],
        "colors": ["Black", "Navy", "Gray"],
        "stock": 20,
        "image": "/images/bestSellingProducts/product-cover-54.png"
    },
    {
        "id": 5,
        "name": "Kids' Cotton T-Shirt",
        "slug": "e",
        "category": "Kids",
        "price": 15.99,
        "description": "Soft and comfortable T-shirt for kids, available in fun prints.",
        "sizes": ["2-4", "4-6", "6"],
        "image": "/images/bestSellingProducts/product-cover-55.png"
    },
    {
        "id": 6,
        "name": "Unisex Hoodie",
        "slug": "f",
        "category": "Unisex",
        "price": 29.99,
        "description": "A cozy unisex hoodie made with soft fleece material.",
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "colors": ["Gray", "Black", "White"],
        "stock": 35,
        "image": "/images/bestSellingProducts/product1.png"
    },
    {
        "id": 7,
        "name": "Women's Yoga Pants",
        "slug": "g",
        "category": "Women",
        "price": 25.99,
        "description": "Stretchable and comfortable yoga pants for women.",
        "sizes": ["S", "M", "L", "XL"],
        "colors": ["Black", "Gray", "Purple"],
        "stock": 45,
        "image": "/images/products/product-cover-5.png"
    },
    {
        "id": 8,
        "name": "Men's Leather Jacket",
        "slug": "h",
        "category": "Men",
        "price": 120.99,
        "description": "A premium leather jacket with a sleek design for men.",
        "sizes": ["M", "L", "XL", "XXL"],
        "colors": ["Black", "Brown"],
        "stock": 15,
        "image": "/images/products/product-cover-5a.png"
    },
    {
        "id": 9,
        "name": "Women's Winter Coat",
        "slug": "i",
        "category": "Women",
        "price": 89.99,
        "description": "A warm and stylish winter coat designed for comfort.",
        "sizes": ["S", "M", "L", "XL"],
        "colors": ["Red", "Black", "Beige"],
        "stock": 25,
        "image": "/images/products/product-cover-5b.png"
    },
    {
        "id": 10,
        "name": "Kids' Raincoat",
        "slug": "j",
        "category": "Kids",
        "price": 22.99,
        "description": "Bright and colorful raincoats to keep kids dry.",
        "sizes": ["S", "M", "L"],
        "colors": ["Yellow", "Blue", "Pink"],
        "stock": 40,
        "image": "/images/products/product-cover-5c.png"
    },
    {
        "id": 11,
        "name": "Men's Sports Shorts",
        "slug": "k",
        "category": "Men",
        "price": 19.99,
        "description": "Comfortable and lightweight sports shorts for active wear.",
        "sizes": ["S", "M", "L", "XL"],
        "colors": ["Black", "Gray", "Navy"],
        "stock": 50,
        "image": "/images/products/product-cover-5d.png"
    },
    {
        "id": 12,
        "name": "Women's Evening Gown",
        "slug": "l",
        "category": "Women",
        "price": 150.99,
        "description": "An elegant evening gown perfect for formal events.",
        "sizes": ["XS", "S", "M", "L"],
        "colors": ["Black", "Blue", "Emerald"],
        "stock": 10,
        "image": "/images/products/product-cover-5e.png"
    },
    {
        "id": 13,
        "name": "Kids' Pajama Set",
        "slug": "m",
        "category": "Kids",
        "price": 18.99,
        "description": "Soft and cozy pajama sets for kids.",
        "sizes": ["2-4", "4-6", "6-8", "8-10"],
        "colors": ["Green", "Yellow", "Pink"],
        "stock": 30,
        "image": "/images/products/product-cover-5f.png"
    },
    {
        "id": 14,
        "name": "Unisex Running Shoes",
        "slug": "n",
        "category": "Unisex",
        "price": 60.99,
        "description": "Lightweight running shoes for everyday use.",
        "sizes": ["6", "7", "8", "9", "10", "11"],
        "colors": ["White", "Gray", "Black"],
        "stock": 25,
        "image": "/images/products/product-cover-5g.png"
    },
    {
        "id": 15,
        "name": "Men's Formal Pants",
        "slug": "o",
        "category": "Men",
        "price": 40.99,
        "description": "Tailored formal pants for a sharp look.",
        "sizes": ["30", "32", "34", "36", "38"],
        "colors": ["Black", "Navy", "Gray"],
        "stock": 35,
        "image": "/images/products/product-cover-51.png"
    },
    {
        "id": 16,
        "name": "Women's Cardigan",
        "slug": "p",
        "category": "Women",
        "price": 28.99,
        "description": "A cozy cardigan perfect for layering.",
        "sizes": ["S", "M", "L", "XL"],
        "colors": ["Beige", "Pink", "Gray"],
        "stock": 20,
        "image": "/images/products/product-cover-52.png"
    },
    {
        "id": 17,
        "name": "Men's Beanie Hat",
        "slug": "q",
        "category": "Men",
        "price": 12.99,
        "description": "A warm beanie hat made from soft wool.",
        "sizes": ["One Size"],
        "colors": ["Black", "Gray", "Navy"],
        "stock": 45,
        "image": "/images/products/product-cover-53.png"
    },
    {
        "id": 18,
        "name": "Women's Scarf",
        "slug": "r",
        "category": "Women",
        "price": 15.99,
        "description": "A lightweight scarf for a chic look.",
        "sizes": ["One Size"],
        "colors": ["Red", "Blue", "White"],
        "stock": 50,
        "image": "/images/products/product-cover-54.png"
    },
    {
        "id": 19,
        "name": "Kids' Winter Gloves",
        "slug": "s",
        "category": "Kids",
        "price": 8.99,
        "description": "Warm and comfortable gloves for kids.",
        "sizes": ["S", "M", "L"],
        "colors": ["Blue", "Pink", "Gray"],
        "stock": 60,
        "image": "/images/products/product-cover-55.png"
    },
    {
        "id": 20,
        "name": "Men's Leather Wallet",
        "slug": "t",
        "category": "Men",
        "price": 25.99,
        "description": "A classic leather wallet with multiple compartments.",
        "sizes": ["One Size"],
        "colors": ["Black", "Brown"],
        "stock": 50,
        "image": "/images/products/product-cover-56.png"
    },
    {
        "id": 21,
        "name": "Women's Clutch Bag",
        "slug": "u",
        "category": "Women",
        "price": 35.99,
        "description": "A stylish clutch bag for evening outings.",
        "sizes": ["One Size"],
        "colors": ["Gold", "Silver", "Black"],
        "stock": 30,
        "image": "/images/products/product-cover-57.png"
    },
    {
        "id": 22,
        "name": "Unisex Socks (Pack of 3)",
        "slug": "v",
        "category": "Unisex",
        "price": 9.99,
        "description": "Comfortable cotton socks in a pack of three.",
        "sizes": ["M", "L"],
        "colors": ["Black", "White", "Gray"],
        "stock": 75,
        "image": "/images/products/product-cover-58.png"
    }


]


export default Data;